version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: jobsdb
      POSTGRES_USER: jobsuser
      POSTGRES_PASSWORD: changemeinprod!

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jobsdb
      SPRING_DATASOURCE_USERNAME: jobsuser
      SPRING_DATASOURCE_PASSWORD: changemeinprod!
    depends_on:
      - db
