version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Optional: you can add any env variables your app needs
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped
